Licenta/Controllers/OrdersController.cs
using Licenta.Model;
using Licenta.ViewModels.Orders;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;
using Licenta.AppLogic.Services;
using Licenta.ViewModels.Customers;

namespace Licenta.Controllers
{
    public class OrdersController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly OrderService orderService;
        private readonly CustomerService customerService;

        public OrdersController(OrderService orderService, CustomerService customerService)
        {
            this.orderService = orderService;
            this.customerService = customerService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult OrdersTable()
        {
            var ordersView = new OrderViewModel();
            if (User.IsInRole("Dispatcher"))
            {
                ordersView.Orders = orderService.GetAllOrders();
            }
            else if (!User.IsInRole("Admin") && !User.IsInRole("Driver") && !User.IsInRole("Dispatcher"))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var senderId = customerService.GetCustomerById(userId).Id.ToString();
                ordersView.Orders = orderService.GetOrdersForCurrentCustomer(senderId);
            }

            return PartialView("_OrdersTablePartial", ordersView);
        }

        private static Microsoft.AspNetCore.Mvc.Rendering.SelectListItem CreateListItem(LocationAddress location)
        {
            var dropdownText = location.Tag == null ? $"{ location.PostalCode }, { location.Street}" : $"{ location.Tag }";
            var selectLocation = new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem(dropdownText, location.Id.ToString());
            return selectLocation;
        }

        private List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> GetCustomerList()
        {
            var customers = customerService.GetAllCustomers();
            var customerNames = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>();

            foreach (var customer in customers)
            {
                if (customer.LocationAddresses.Count > 0)
                {
                    customerNames.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem(customer.Name, customer.Id.ToString()));
                }
            }
            return customerNames;
        }

        private List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> GetLocationsList(string customerId)
        {
            var locations = customerService.GetCustomerAddresses(customerId);

            return locations.Select(CreateListItem).ToList();
        }

        [Microsoft.AspNetCore.Mvc.HttpGet]
        public IActionResult NewOrder(string id)
        {
            var pickupLocations = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>();
            var deliveryLocations = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>();
            var unchosenLocations = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>();
            string senderId = null;
            string pickupId = null;
            string deliveryId = null;

            try
            {
                if (id != null)
                {
                    var splitId = id.Split(';');
                    senderId = splitId[0];
                    var locationId = splitId[1];
                    var locationType = splitId[3];

                    string secondLocationId = null;
                    if (locationId != splitId[2])
                    {
                        secondLocationId = splitId[2];
                    }

                    if (customerService.IsLocation(locationId))
                    {
                        var chosenLocation = customerService.GetLocationAddress(locationId);
                        var customer = customerService.GetCustomerById(senderId);

                        unchosenLocations.AddRange(from location in customer.LocationAddresses where location.Id != chosenLocation.Id select CreateListItem(location));

                        if (locationType.Equals(NewOrderViewModel.LocationType.Pickup.ToString()))
                        {
                            pickupId = locationId;
                            deliveryId = secondLocationId;
                            pickupLocations.Add(CreateListItem(chosenLocation));
                            pickupLocations.AddRange(unchosenLocations);
                            deliveryLocations.AddRange(unchosenLocations);
                        }

                        if (locationType.Equals(NewOrderViewModel.LocationType.Delivery.ToString()))
                        {
                            deliveryId = locationId;
                            pickupId = secondLocationId;
                            deliveryLocations.Add(CreateListItem(chosenLocation));
                            deliveryLocations.AddRange(unchosenLocations);
                            pickupLocations.AddRange(unchosenLocations);
                        }
                    }
                    else
                    {
                        var locations = GetLocationsList(senderId);
                        pickupLocations.AddRange(locations);
                        deliveryLocations.AddRange(locations);
                        deliveryLocations.RemoveAt(0);
                    }
                }

                if (senderId == null && GetCustomerList().Count > 0)
                {
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    senderId = customerService.GetCustomerById(userId).Id.ToString();
                    pickupLocations.AddRange(GetLocationsList(senderId));
                    deliveryLocations.AddRange(GetLocationsList(senderId));
                    deliveryLocations.RemoveAt(0);
                }

                var newOrderViewModel = new NewOrderViewModel()
                {
                    CustomerList = GetCustomerList(),
                    PickupLocations = pickupLocations,
                    DeliveryLocations = deliveryLocations,
                    SenderId = senderId,
                    DeliveryLocationId = deliveryId,
                    PickupLocationId = pickupId
                };

                return PartialView("_NewOrderPartial", newOrderViewModel);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public IActionResult NewOrder([FromForm] NewOrderViewModel orderData)
        {
            try
            {
                var sender = customerService.GetCustomerById(orderData.SenderId);

                if (orderData.PickupLocationId == null && orderData.DeliveryLocationId == null)
                {
                    return PartialView("_NewOrderPartial", orderData);
                }
                if (orderData.PickupLocationId == null || orderData.DeliveryLocationId == null)
                {
                    var bonusLocation = LocationAddress.Create(orderData.Country,
                        orderData.City, orderData.Street,
                        orderData.StreetNumber, orderData.PostalCode, null);

                    customerService.AddLocation(bonusLocation);

                    orderData.PickupLocationId ??= bonusLocation.Id.ToString();

                    orderData.DeliveryLocationId ??= bonusLocation.Id.ToString();
                }
                
                var recipient = orderService.CreateNewRecipient(orderData.RecipientName,
                            orderData.RecipientPhoneNo,
                            orderData.RecipientEmail);
                var awb = CreateAwb(8);
                orderData.Awb = awb;
                orderService.CreateOrder(recipient,
                    sender,
                    orderData.PickupLocationId,
                    orderData.DeliveryLocationId,
                    orderData.Price,
                    orderData.Awb);
                return PartialView("_NewOrderPartial", orderData);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public string GetAwb(string awb)
        {
            var response = orderService.GetByAwb(awb);
            return response != null ? $"Your order is {response.Status}" : "No order found with the specific AWB";
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public Microsoft.AspNetCore.Mvc.JsonResult ActionName(string yourValue)
        {

            return Json(new { success = true, result = yourValue }, JsonRequestBehavior.AllowGet);
        }

        private static readonly Random Rd = new Random();
        internal static string CreateAwb(int stringLength)
        {
            const string allowedChars = "ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789";
            var chars = new char[stringLength];

            for (var i = 0; i < stringLength; i++)
            {
                chars[i] = allowedChars[Rd.Next(0, allowedChars.Length)];
            }

            return new string(chars);
        }
    }
}

Licenta/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Licenta.Controllers
{
    public class ProfileController : Controller
    {
        // GET: ProfileController
        public IActionResult Index()
        {
            return View();
        }

        // GET: ProfileController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProfileController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProfileController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfileController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProfileController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfileController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProfileController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Licenta/Controllers/VehiclesController.cs
using Licenta.ViewModels.Vehicles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using Licenta.AppLogic.Services;

namespace Licenta.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly VehicleService vehicleService;
        private readonly DriverService driverService;
        private readonly ILogger<VehicleService> logger;

        public VehiclesController(VehicleService vehicleService,
                                  ILogger<VehicleService> logger,
                                  DriverService driverService)
        {
            this.vehicleService = vehicleService;
            this.logger = logger;
            this.driverService = driverService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var viewModel = new VehiclesListViewModel
                {
                    Vehicles = vehicleService.GetAll(),
                    Drivers = driverService.GetAllDrivers()
                };
                return View(viewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to retrieve vehicle list {@Exception}", e.Message);
                logger.LogDebug("Failed to retrieve vehicle list {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        public IActionResult VehiclesTable()
        {
            try
            {
                var viewModel = new VehiclesListViewModel
                {
                    Vehicles = vehicleService.GetAll(),
                    Drivers = driverService.GetAllDrivers()
                };
                return PartialView("_VehiclesTable", viewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to retrieve vehicle list {@Exception}", e.Message);
                logger.LogDebug("Failed to retrieve vehicle list {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            return PartialView("_Create", new NewVehicleViewModel());
        }

        [HttpPost]
        public IActionResult Create([FromForm] NewVehicleViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_Create", new NewVehicleViewModel());
            }

            try
            {
                vehicleService.Add(viewModel.Name,
                                   viewModel.Type,
                                   viewModel.RegistrationNumber,
                                   viewModel.MaximCarryWeight,
                                   viewModel.Vin);
                return PartialView("_Create", new NewVehicleViewModel());
            }
            catch (Exception e)
            {
                logger.LogError("Failed to create a new vehicle {@Exception}", e.Message);
                logger.LogDebug("Failed to create a new vehicle {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        public IActionResult Remove(string id)
        {
            try
            {
                vehicleService.Remove(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                logger.LogError("Failed to remove a vehicle {@Exception}", e.Message);
                logger.LogDebug("Failed to remove a vehicle {ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            try
            {
                var vehicleFromDb = vehicleService.GetById(id);
                var viewModel = new UpdateVehicleViewModel
                {
                    Id = id,
                    NameUpdate = vehicleFromDb.Name,
                    Type = vehicleFromDb.Type,
                    RegistrationNumber = vehicleFromDb.RegistrationNumber,
                    MaximCarryWeight = vehicleFromDb.MaximCarryWeightKg,
                    Vin = vehicleFromDb.Vin
                };
                return PartialView("_Update", viewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to retrieve vehicle {@Exception}", e.Message);
                logger.LogDebug("Failed to retrieve vehicle {ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        public IActionResult Update([FromForm] UpdateVehicleViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_Update", viewModel);
            }

            try
            {
                vehicleService.Update(viewModel.Id,
                                      viewModel.NameUpdate,
                                      viewModel.Type,
                                      viewModel.RegistrationNumber,
                                      viewModel.MaximCarryWeight,
                                      viewModel.Vin);
                return PartialView("_Update", viewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to update vehicle {@Exception}", e.Message);
                logger.LogDebug("Failed to update vehicle {ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        [HttpGet]
        public IActionResult History(string id)
        {
            try
            {
                var viewModel = new HistoryVehicleViewModel
                {
                    Vehicle = vehicleService.GetById(id),
                    VehicleDriver = vehicleService.GetHistory(id)
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to retrieve vehicle {@Exception}", e.Message);
                logger.LogDebug("Failed to retrieve vehicle {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }
    }
}

Licenta/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<style>
    color {
        color: lightseagreen;
        animation-name: example;
        animation-duration: 4s;
        animation-iteration-count:infinite;
    }

    @@keyframes example {

      50%  {color: blue;}

}
</style>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Licenta</title>
    <link rel="stylesheet" href="~/css/maicons.css" />
    <link rel="stylesheet" href="~/vendor/animate/animate.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/theme.css" />
    <link href="~/lib/fontawesome/css/fontawesome.css" rel="stylesheet">
    <link href="~/lib/fontawesome/css/solid.css" rel="stylesheet">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Calcite Maps -->
    <link rel="stylesheet" href="https://esri.github.io/calcite-maps/dist/css/calcite-maps-arcgis-4.x.min-v0.8.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/rowreorder/1.2.8/css/rowReorder.dataTables.min.css">
    <!-- ArcGIS JS 4 -->
    <link rel="stylesheet" href="https://js.arcgis.com/4.10/esri/css/main.css">
    <partial name="_ValidationScriptsPartial" />
</head>
<body>
    <div class="back-to-top"></div>
    <header>
        <nav style="background-color: #121212 !important; font-size:25px" class="navbar navbar-expand-lg navbar-light bg-white sticky" data-offset="30">
            <div class="container-fluid" style="margin-left: auto; margin-right: 0;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Licenta</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapsed text-start" style="margin-left: auto; margin-right: 0;" id="navbarContent">
                    <ul class="navbar-nav ml-auto text-start" style="margin-left: auto; margin-right: 0;">
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                        <li class="nav-item">
                            <a asp-controller="Administrators" asp-action="Index"><img width="50" height="50" src="~/img/Icons/accounts.svg" /> Accounts</a>
                            
                        </li>
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Dispatcher"))
                        {
                            
                            @*<li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Drivers" asp-action="DriversTable">
                                    <em class="fas fa-shipping-fast"></em>
                                    Drivers
                                </a>
                            </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Vehicles" asp-action="Index">
                                    <img width="50" height="50" src="~/img/Icons/delivery-truck-truck-svgrepo-com.svg"/>
                                    Vehicles
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Orders" asp-action="Index">
                                    <img width="50" height="50" src="~/img/Icons/box-svgrepo-com.svg" />
                                    Orders
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Dispatchers" asp-action="Index">
                                    <img width="50" height="50" src="~/img/Icons/delivery-man-driver-svgrepo-com.svg" />
                                    Drivers
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Routes" asp-action="Index">
                                    <img width="50" height="50" src="~/img/Icons/route-start-svgrepo-com.svg" />
                                    Routes
                                </a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Driver"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Drivers" asp-action="Index">
                                    <img width="50" height="50" src="~/img/Icons/route-start-svgrepo-com.svg" />
                                    View Route
                                </a>
                            </li>
                        }
                        </ul>
                    </div>
                        <div class="navbar-collapse collapsed text-end" style="margin-left: auto; margin-right: 0;" id="navbarContent">
                            <ul class="navbar-nav ml-auto text-end" style="margin-left: auto; margin-right: 0;">
                                @if (SignInManager.IsSignedIn(User) && !User.IsInRole("Admin"))
                                {
                                    <li class="nav-item" style="margin-left: auto; margin-right: 0;">
                                        <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                                    </li>
                                    <li class="nav-item">
                                        <form class="form-inline " asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button style="border-radius:100px"><img width="50" height="50" src="~/img/Icons/exit-svgrepo-com.svg" /></button>
                                        </form>
                                    </li>
                                }
                                else if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                                {
                                    <li class="nav-item" style="margin-left: auto; margin-right: 0;">
                                        <a class="nav-link text-white" title="Manage">Hello @User.Identity.Name!</a>
                                    </li>
                                    <li class="nav-item">
                                        <form class="form-inline " asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button style="border-radius:100px"><img width="50" height="50" src="~/img/Icons/exit-svgrepo-com.svg" /></button>
                                        </form>
                                    </li>
                                }
                            </ul>
                        </div>
                </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*@if (SignInManager.IsSignedIn(User) && Context.Request.Path != "/Identity/Account/(a-zA-Z)+")
    {<a asp-controller="Profile" asp-action="Index">
            <footer class="page-footer" style="clip-path: circle(15% at 50% 180%); padding-top: 55px; height:130px;">

                <div style="font-size:20px; color: black; font-weight:bold;">Last Shippment Status</div>

                <color style="font-size:20px; color: lightseagreen; font-weight:bold; height:30px">Order Status </color>
            </footer>
        </a>
    }*@
    <script src="~/js/jquery-3.5.1.min.js"></script>

    <script src="~/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/google-maps.js"></script>

    <script src="~/vendor/wow/wow.min.js"></script>

    <script src="~/js/theme.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>