Licenta/ViewModels/Dispatchers/AssignRouteViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Licenta.ViewModels.Dispatchers
{
    public class AssignRouteViewModel
    {
        public string DriverId { get; set; }
        [Required(ErrorMessage = "Choosing a route is required.")]
        [Display(Name = "Route:")]
        public string RouteId { get; set; }

        public List<SelectListItem> RouteList { get; set; }
    }
}

Licenta/ViewModels/Dispatchers/DriversListViewModel.cs
using Licenta.Model;
using System.Collections.Generic;

namespace Licenta.ViewModels.Dispatchers
{
    public class DriversListViewModel
    {
        public IEnumerable<Driver> Drivers { get; set; }

        public IEnumerable<Route> Routes { get; set; }

    }
}

Licenta/Controllers/DispatchersController.cs
using Licenta.ViewModels.Dispatchers;
using Licenta.ViewModels.Routes;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using Licenta.AppLogic.Services;

namespace Licenta.Controllers
{
    public class DispatchersController : Controller
    {

        private readonly DriverService driverService;
        private readonly ILogger<DriverService> logger;
        private readonly VehicleService vehicleService;
        private readonly RouteService routeService;
        private readonly UserManager<IdentityUser> userManager;
        private readonly DispatcherService dispatcherService;
        public DispatchersController(DriverService driverService, ILogger<DriverService> logger
            , VehicleService vehicleService, UserManager<IdentityUser> userManager, DispatcherService dispatcherService,
            RouteService routeService)
        {
            this.driverService = driverService;
            this.logger = logger;
            this.vehicleService = vehicleService;
            this.userManager = userManager;
            this.dispatcherService = dispatcherService;
            this.routeService = routeService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DriversTable()
        {
            try
            {
                var driversViewModel = new DriversListViewModel()
                {
                    Drivers = driverService.GetAllDrivers()
                };

                return PartialView("_DriversTablePartial", driversViewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to load Driver entities {@Exception}", e.Message);
                logger.LogDebug("Failed to load Driver entities {@ExceptionMessage}", e);
                return BadRequest("Failed to load Driver entities");
            }

        }
        [HttpGet]
        public IActionResult AssignRoute([FromRoute] string id)
        {
            var driverId = id;
            var assignRouteViewModel = new AssignRouteViewModel
            {
                DriverId = driverId,
                RouteList = GetRouteList()
            };
            return PartialView("_AssignRoutePartial", assignRouteViewModel);

        }

        [HttpPost]
        public IActionResult AssignRoute([FromForm] AssignRouteViewModel data)
        {
            var userId = userManager.GetUserId(User);
            var dispatcherDb = dispatcherService.GetByUserId(userId);

            if (ModelState.IsValid)
            {
                var driver = driverService.GetByUserId(data.DriverId);
                var route = routeService.GetById(data.RouteId);
                foreach(var entry in route.RouteEntries)
                {
                    entry.Order.SetStatus(Model.OrderStatus.Assigned);
                }
                dispatcherService.ConnectDriverToRoute(route, driver);
            }
            return PartialView("_AssignRoutePartial", data);

        }

        [HttpGet]
        public IActionResult RemoveRouteFromDriver([FromRoute] string id)
        {

            var removeViewModel = new RemoveRouteViewModel()
            {
                Id = id
            };

            return PartialView("_RemoveRoutePartial", removeViewModel);
        }

        [HttpPost]
        public IActionResult RemoveRouteFromDriver(RemoveRouteViewModel removeData)
        {

            routeService.DeselectRoute(removeData.Id);

            return PartialView("_RemoveRoutePartial", removeData);
        }
        private List<SelectListItem> GetRouteList()
        {
            var routes = routeService.GetAllRoutes();
            var routesNames = new List<SelectListItem>();

            foreach (var route in routes)
            {
                var text = route.Vehicle.Name + " " + route.StartTime;
                routesNames.Add(new SelectListItem(text, route.Id.ToString()));
            }
            return routesNames;
        }

    }
}

Licenta/Controllers/RoutesController.cs
using Licenta.Model;
using Licenta.ViewModels.Routes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using Licenta.AppLogic.Services;


namespace Licenta.Controllers
{
    public class RoutesController : Controller
    {

        private readonly ILogger<RouteService> logger;
        private readonly RouteService routeService;
        private readonly VehicleService vehicleService;
        private readonly OrderService orderService;
        public RoutesController(ILogger<RouteService> logger, RouteService routeservice, VehicleService vehicleService, OrderService orderService)
        {
            this.logger = logger;
            routeService = routeservice;
            this.vehicleService = vehicleService;
            this.orderService = orderService;
        }

        public IActionResult Index()
        {
            return View();
        }

        private List<SelectListItem> GetVehicleList()
        {
            var vehicles = vehicleService.GetAll();

            var vehicleNames = new List<SelectListItem>();

            foreach (var vehicle in vehicles)
            {
                if (vehicle.Status == VehicleStatus.Free)
                {
                    vehicleNames.Add(new SelectListItem(vehicle.Name, vehicle.Id.ToString()));
                }
            }
            return vehicleNames;
        }
        private List<SelectListItem> GetOrderList()
        {
            var orders = orderService.GetAllOrders();
            var orderNames = new List<SelectListItem>();

            foreach (var order in orders)
            {
                var text = order.DeliveryAddress.PostalCode + " " + order.DeliveryAddress.Street;
                orderNames.Add(new SelectListItem(text, order.Id.ToString()));
            }
            return orderNames;
        }

        private List<SelectListItem> GetUnfinishedOrderList()
        {
            var orders = orderService.GetUnfinishedOrders();
            var orderNames = new List<SelectListItem>();

            foreach (var order in orders)
            {
                var text = order.DeliveryAddress.PostalCode + " " + order.DeliveryAddress.Street;
                orderNames.Add(new SelectListItem(text, order.Id.ToString()));
            }
            return orderNames;
        }

        private List<SelectListItem> GetOrderListFromRoute(string id)
        {
            var route = routeService.GetById(id);

            var routes = route.RouteEntries;

            return routes.Select(order => new SelectListItem(order.Order.DeliveryAddress.Street, order.Id.ToString())).ToList();
        }

        [HttpGet]
        public IActionResult AddOrder(string routeId)
        {
            try
            {
                var newOrderViewModel = new AddOrderViewModel()
                {
                    OrderList = GetOrderList(),
                    RouteId = routeId,
                    OrderType = GetOrderType()
                };
                return PartialView("_AddOrderPartial", newOrderViewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to load information for Order {@Exception}", e.Message);
                logger.LogDebug("Failed to load information for Order {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        private List<SelectListItem> GetOrderType()
        {

            var orderNames = new List<SelectListItem>
            {
                new SelectListItem("Both", OrderType.Both.ToString()),
                new SelectListItem("Delivery", OrderType.Delivery.ToString()),
                new SelectListItem("PickUp", OrderType.PickUp.ToString())
            };
            return orderNames;
        }

        [HttpPost]
        public IActionResult AddOrder([FromForm] AddOrderViewModel orderData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var order = orderService.GetById(orderData.OrderId);
                    var route = routeService.GetById(orderData.RouteId);
                    var entry = new RouteEntry() { Id = Guid.NewGuid() };
                    entry.SetOrder(order);
                    order.SetStatus(OrderStatus.Assigned);
                    entry.SetOrder(order);
                    entry.SetType(orderData.Type);
                    routeService.AddEntry(route.Id.ToString(), entry);
                }
                return PartialView("_AddOrderPartial", orderData);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to create a new Order {@Exception}", e.Message);
                logger.LogDebug("Failed to create a new Order {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        [HttpGet]
        public IActionResult OrderList(string id)
        {
            var splitId = id.Split(';');
            var orderId = splitId[0];
            var routeId = splitId[1];

            var model = new AddOrderViewModel()
            {
                OrderId = orderId,
                OrderList = GetUnfinishedOrderList(),
                RouteId = routeId

            };
            return PartialView("_AddOrderPartial", model);

        }

        [HttpPost]
        public IActionResult OrderList([FromForm] AddOrderViewModel data)
        {
            return AddOrder(data.RouteId);
        }

        [HttpGet]
        public IActionResult NewRoute(string id)
        {
            try
            {
                var vehicleId = id ?? throw new ArgumentNullException(nameof(id));
                var newRouteViewModel = new NewRouteViewModel()
                {
                    VehicleId = vehicleId,
                    VehicleList = GetVehicleList()
                };

                return PartialView("_NewRoutePartial", newRouteViewModel);
            }

            catch (Exception e)
            {
                logger.LogError("Failed to load information for Route {@Exception}", e.Message);
                logger.LogDebug("Failed to load information for Route {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        public IActionResult NewRoute([FromForm] NewRouteViewModel routeData)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var vehicle = vehicleService.GetById(routeData.VehicleId);

                    routeService.CreateRoute(vehicle);


                    return PartialView("_NewRoutePartial", routeData);
                }

                return PartialView("_NewRoutePartial", routeData);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to create a new Route {@Exception}", e.Message);
                logger.LogDebug("Failed to create a new Route {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }

        public IActionResult RoutesTable()
        {
            var routesView = new RouteViewModel()
            {
                Routes = routeService.GetAllRoutes()
            };
            return PartialView("_RoutesTablePartial", routesView);
        }


        [HttpGet]
        public IActionResult Remove([FromRoute] string id)
        {

            var removeViewModel = new RemoveRouteViewModel()
            {
                Id = id
            };

            return PartialView("_RemoveRoutePartial", removeViewModel);
        }

        [HttpPost]
        public IActionResult Remove(RemoveRouteViewModel removeData)
        {

            routeService.RemoveRoute(removeData.Id);

            return PartialView("_RemoveRoutePartial", removeData);
        }

        [HttpGet]
        public IActionResult RemoveOrderList([FromRoute] string id)
        {
            var splitId = id.Split(';');
            var routeId = splitId[1];

            var model = new DeleteOrderViewModel()
            {
                OrderList = GetOrderListFromRoute(routeId),
                RouteId = routeId

            };
            return PartialView("_RemoveOrderPartial", model);
        }

        [HttpPost]
        public IActionResult RemoveOrderList([FromForm] DeleteOrderViewModel data)
        {
            return RemoveOrder(data.RouteId);


        }

        [HttpGet]
        public IActionResult RemoveOrder(string routeId)
        {
            try
            {
                var newOrderViewModel = new DeleteOrderViewModel()
                {
                    OrderList = GetOrderList(),
                    RouteId = routeId
                };
                return PartialView("_RemoveOrderPartial", newOrderViewModel);
            }
            catch (Exception e)
            {
                logger.LogError("Failed to load information for Order {@Exception}", e.Message);
                logger.LogDebug("Failed to load information for Order {@ExceptionMessage}", e);
                return BadRequest(e.Message);
            }
        }
        [HttpPost]
        public IActionResult RemoveOrder([FromForm] DeleteOrderViewModel orderData)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var routeEntry = routeService.GetEntryById(orderData.OrderId);
                    var route = routeService.GetById(orderData.RouteId);
                    var order = routeService.GetOrderIdFromEntry(routeEntry.Id);
                    order.SetStatus(OrderStatus.Created);
                    routeService.RemoveEntry(route.Id.ToString(), routeEntry);


                }
                return PartialView("_RemoveOrderPartial", orderData);
            }
            catch (Exception e)
            {

Licenta/Views/Dispatchers/Index.cshtml
@using Licenta.ViewModels.Dispatchers
@using Licenta.ViewModels.Routes

<link rel="stylesheet" type="text/css" href="~/lib/datatables/datatables.min.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.bootstrap4.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.dataTables.min.css" />

<div class="row d-flex justify-content-between mt-3 mb-3 mr-auto">
    <h1 class="ml-3">Drivers</h1>
    
</div>

<div id="driversTableContainer"></div>

<form method="post" asp-controller="Dispatchers" asp-action="AssignRoute"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="modalFormComplete('#assignRouteModal')"
      data-ajax-mode="replace"
      data-ajax-update="#assignRouteBody">

    <div class="modal fade" id="assignRouteModal" tabindex="-1" aria-labelledby="assignRouteTitle" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center">
            <div class="modal-content" style="max-width: 70%">
                <div class="modal-header">
                    <h5 class="modal-title" id="assignRouteTitle">Assign Route</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="assignRouteBody">
                    <partial name="_AssignRoutePartial" model="new AssignRouteViewModel()" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Assign</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-controller="Dispatchers" asp-action="RemoveRouteFromDriver"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="replace"
      data-ajax-complete="modalFormComplete('#removeModal')"
      data-ajax-update="#removeBody">

    <div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center" role="document">
            <div class="modal-content" style="max-width: 60%">
                <div class="modal-body" id="removeBody">
                    <partial name="_RemoveRoutePartial" model="new RemoveRouteViewModel()" />
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script type="text/javascript" src="~/lib/datatables/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/datatables/Responsive-2.2.3/js/dataTables.responsive.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            loadTable();
        });

        function loadTable() {
            loadServerPartialView("#driversTableContainer", "/Dispatchers/DriversTable").done(function () {
                $('#driversTable').DataTable({ responsive: true, "lengthMenu": [5, 10, 25, 50] });
            });
        }

        function modalFormComplete(modalName) {
            $(modalName).modal("hide");
            loadTable();
        }

        function goToVehicles() {
            document.location = '@Url.Action("Index", "Vehicles")';
        }

        function LoadShowEntryView(entryId) {
            loadServerPartialView("#showEntryBody", '@Url.Action("ShowEntry", "Routes")' + "/" + entryId);
        }

        function loadAvailableRoutes(DriverId) {
            $('#DriverId').val(DriverId);
            driverId = DriverId;
            loadServerPartialView("#assignRouteBody", '@Url.Action("AssignRoute", "Dispatchers")' + "/" + DriverId).
                done(function () {
                    LoadDropdownRoute('#RouteId', driverId);
                });
        }

        function LoadDropdownRoute(Id, driverId) {
            var RouteId = $(Id).val();
            loadServerPartialView("#assignRouteBody", '@Url.Action("GetRouteList", "Dispatchers")' + "/" + RouteId + ';' + driverId);
        }

         function LoadRemoveRouteView(Id) {
             loadServerPartialView("#removeBody",'@Url.Action("RemoveRouteFromDriver", "Dispatchers")' + "/" + Id);
        }

    </script>
}

Licenta/Views/Dispatchers/_AssignRoutePartial.cshtml
@using Licenta.ViewModels.Dispatchers;
@model AssignRouteViewModel

<input type="hidden" asp-for="DriverId" />

<div class="form-group text-center">
    <label asp-for="RouteId"></label>
    <div class=" d-flex justify-content-around align-text-bottom">
        <select style="min-width: 60%" asp-for="RouteId" asp-items="@Model.RouteList">
        </select>
    </div>
    <span asp-validation-for="RouteId" class="text-danger"></span>
</div>

Licenta/Views/Dispatchers/_DriversTablePartial.cshtml
@using Licenta.ViewModels.Dispatchers
@model DriversListViewModel

<table id="driversTable" class="table table-striped table-bordered" style="width:100%">
    <thead class="dropdown text-center">
        <tr>
            <th>Driver ID</th>
            <th>Current Route</th>
            <th>Status</th>
            <th>Assign Route</th>
        </tr>
    </thead>

    <tbody>

        @foreach (var driver in Model.Drivers)
        {
            <tr>
                <td class="dropdown text-center">
                    <button class="btn btn-blue dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @driver.UserId
                    </button>
                    <div class="dropdown-menu dropdown-menu-style">
                        <div>Name:</div>
                        <h6>@driver.Name</h6>
                        <div>Email:</div>
                        <h6>@driver.Email</h6>
                    </div>
                </td>
                <td class="dropdown text-center" style="width: 25%">
                    @if (driver.CurrentRoute != null)
                    {
                        <button class="btn btn-blue dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Orders on route: @driver.CurrentRoute.RouteEntries.Count()
                        </button>

                        <div class="dropdown-menu">
                            @foreach (var routeEntry in driver.CurrentRoute.RouteEntries)
                            {
                                <button class="dropdown-item btn-blue edit-dropdown-item" data-toggle="modal"
                                        onclick="LoadShowEntryView('@routeEntry.Id')" data-target="#showEntryModal">

                                    <div>
                                        <em class="fas fa-info-circle"></em>
                                        @routeEntry.OrderType, Status: @routeEntry.Order.Status, Route:
                                        @routeEntry.Order.PickUpAddress.PostalCode
                                        - @routeEntry.Order.DeliveryAddress.PostalCode
                                    </div>
                                </button>
                            }
                        </div>
                    }
                    else
                    {
                        <div class="text-center">No current route</div>
                    }
                </td>

                <td class="text-center">@driver.Status</td>
                <td class="text-center">
                    @if (driver.CurrentRoute == null)
                    {
                        <a data-toggle="modal" data-target="#assignRouteModal" onclick='loadAvailableRoutes("@driver.UserId")'
                           class="button-add-trailer-to-vehicle" style="color: #0366d6; cursor: pointer;">
                            <em class="fa fa-plus-circle"></em>
                            <span>Add</span>
                        </a>
                    }
                    else
                    {
                        <div class="text-center">Assigned</div>
                        <button class="btn btn-outline-danger remove-route-button ml-3 mr-3" title="Remove Route" data-toggle="modal"
                                onclick="LoadRemoveRouteView('@driver.CurrentRoute.Id');" data-target="#removeModal">
                            <div class="col d-flex justify-content-around">
                                <em class="material-icons fa fa-trash"></em>
                                <em class="material-icons fa fa-route"></em>
                            </div>
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Licenta/Views/Dispatchers/_RemoveRoutePartial.cshtml
@using Licenta.ViewModels.Routes;

@model RemoveRouteViewModel;

<input type="hidden" asp-for="Id" />

<div class="text-center">
    <h2>Are you sure?</h2>

</div>
<div class="d-flex justify-content-around">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
    <button type="submit" class="btn btn-success">Yes</button>
</div>