Licenta/ViewModels/Drivers/CurrentRouteViewModel.cs
using Licenta.Model;
using System;
using System.Collections.Generic;

namespace Licenta.ViewModels.Drivers
{
    public class CurrentRouteViewModel
    {

        public ICollection<RouteEntry> RouteEntries { get; set; }
        public Guid DriverId { get; set; }

    }
}

Licenta/ViewModels/Drivers/DriversViewModel.cs
using Licenta.Model;
using System.Collections.Generic;

namespace Licenta.ViewModels.Drivers
{
    public class DriversViewModel
    {
        public IEnumerable<Driver> Drivers { get; set; }
    }
}

Licenta/ViewModels/Drivers/EditInfoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Drivers
{
    public class EditInfoViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "PhoneNumber")]
        public string PhoneNumber { get; set; }
    }
}

Licenta/ViewModels/Drivers/RoutesHistoryViewModel.cs
using Licenta.Model;
using System.Collections.Generic;
using System.Linq;

namespace Licenta.ViewModels.Drivers
{
    public class RoutesHistoryViewModel
    {
        public List<Route> Routes { get; set; }
        public RoutesHistoryViewModel()
        {
            Routes = new List<Route>();
        }
        public void ConfigureRoutes(ICollection<Route> routes)
        {
            Routes = routes.ToList();

        }

    }
}

Licenta/ViewModels/Routes/AddOrderViewModel.cs
using Licenta.Model;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Routes
{
    public class AddOrderViewModel
    {
        public string RouteId { get; set; }

        [Required(ErrorMessage = "Choosing an Order is required.")]
        [Display(Name = "Order:")]
        public string OrderId { get; set; }
        public List<SelectListItem> OrderList;

        [Required(ErrorMessage = "Choosing a type is required.")]
        [Display(Name = "Type:")]
        public OrderType Type { get; set; }
        public List<SelectListItem> OrderType;

    }
}

Licenta/ViewModels/Routes/ChangeVehicleViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Routes
{
    public class ChangeVehicleViewModel
    {
        public string RouteId { get; set; }
        [Required(ErrorMessage = "Choosing a vehicle is required.")]
        [Display(Name = "Vehicle:")]
        public string VehicleId { get; set; }

        public List<SelectListItem> VehicleList { get; set; }
    }
}

Licenta/ViewModels/Routes/DeleteOrderViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Routes
{
    public class DeleteOrderViewModel
    {
        public string RouteId { get; set; }

        [Required(ErrorMessage = "Choosing an Order is required.")]
        [Display(Name = "Order:")]
        public string OrderId { get; set; }
        public List<SelectListItem> OrderList;
    }
}

Licenta/ViewModels/Routes/NewRouteViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Routes
{
    public class NewRouteViewModel
    {
        public List<string> OrderIds { get; set; }

        [Required(ErrorMessage = "Choosing a vehicle is required.")]
        [Display(Name = "Vehicle:")]
        public string VehicleId { get; set; }

        public List<SelectListItem> VehicleList { get; set; }
        public List<SelectListItem> OrderList { get; set; }


    }
}

Licenta/ViewModels/Routes/RemoveRouteViewModel.cs
namespace Licenta.ViewModels.Routes
{
    public class RemoveRouteViewModel
    {
        public string Id { get; set; }
    }
}

Licenta/ViewModels/Routes/RouteEntriesViewModel.cs
using Licenta.Model;
using System.Collections.Generic;

namespace Licenta.ViewModels.Routes
{
    public class RouteEntriesViewModel
    {
        public ICollection<RouteEntry> RouteEntries { get; set; }
    }
}

Licenta/ViewModels/Routes/RouteEntryViewModel.cs
using Licenta.Model;

namespace Licenta.ViewModels.Routes
{
    public class RouteEntryViewModel
    {
        public RouteEntry RouteEntry { get; set; }
    }
}

Licenta/ViewModels/Routes/RouteViewModel.cs
using Licenta.Model;
using System.Collections.Generic;


namespace Licenta.ViewModels.Routes
{
    public class RouteViewModel
    {

        public IEnumerable<Route> Routes { get; set; }

    }
}

Licenta/Controllers/DriversController.cs
using Licenta.Model;
using Licenta.ViewModels.Drivers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using Licenta.AppLogic.Services;

namespace Licenta.Controllers
{
    public class DriversController : Controller
    {
        public DriversController(UserManager<IdentityUser> userManager, DriverService driverService, OrderService orderService,
            ILogger<DriversController> logger, VehicleService vehicleService)
        {
            UserManager = userManager;
            DriverService = driverService;
            OrderService = orderService;
            VehicleService = vehicleService;
            Logger = logger;
        }
        private readonly UserManager<IdentityUser> UserManager;
        private readonly VehicleService VehicleService;
        private readonly DriverService DriverService;
        private readonly OrderService OrderService;
        private readonly ILogger Logger;
        public async Task<IActionResult> Index()

        {

            var user = await UserManager.GetUserAsync(User);
            try
            {
                var driver = DriverService.GetByUserId(user.Id);

                var routeEntries = DriverService.GetRouteEntries(driver.Id);

                var currentRoute = new CurrentRouteViewModel();
                currentRoute.RouteEntries = routeEntries;
                currentRoute.DriverId = driver.Id;

                return View(currentRoute);
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve driver's route entries {@Exception}", e);
                Logger.LogError("Failed to retrieve driver's route entries{Exception}", e.Message);
                return BadRequest();
            }
        }
        public IActionResult SetOrderStatus(OrderStatus status, Guid orderId)
        {
            try
            {
                OrderService.ChangeOrderStatus(orderId, status);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to set order status {@Exception}", e);
                Logger.LogError("Failed to set order status {Exception}", e.Message);
                return BadRequest();
            }

        }
        public async Task<IActionResult> GetOrdersPartial()
        {
            var user = await UserManager.GetUserAsync(User);
            try
            {
                var driver = DriverService.GetByUserId(user.Id);
                var routeEntries = DriverService.GetRouteEntries(driver.Id);

                var currentRoute = new CurrentRouteViewModel();
                currentRoute.RouteEntries = routeEntries;
                currentRoute.DriverId = driver.Id;
                return PartialView("_OrdersTablePartial", currentRoute);
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve driver's route entries {@Exception}", e);
                Logger.LogError("Failed to retrieve driver's route entries {Exception}", e.Message);
                return BadRequest();
            }

        }
        public IActionResult EndRoute()
        {
            var user = UserManager.GetUserAsync(User).GetAwaiter().GetResult();
            try
            {
                var driver = DriverService.GetByUserId(user.Id);
                DriverService.EndCurrentRoute(driver);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to end route {@Exception}", e);
                Logger.LogError("Failed to end route {Exception}", e.Message);
                return BadRequest();
            }
        }
        public async Task<IActionResult> StartRoute()
        {
            var user = await UserManager.GetUserAsync(User);
            try
            {

                var driver = DriverService.GetDriverWithRouteFromUserId(user.Id);
                DriverService.SetDriverStatus(driver, DriverStatus.Driving);
                foreach(var entry in driver.CurrentRoute.RouteEntries)
                {
                    OrderService.ChangeOrderStatus(entry.Order.Id, OrderStatus.Delivering);
                }
                // set order status to delivering
                return RedirectToAction("GetOrdersPartial");
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve users accounts {@Exception}", e);
                Logger.LogError("Failed to retrieve users accounts {Exception}", e.Message);
                return BadRequest();
            }
        }
        public async Task<IActionResult> RoutesHistory()
        {
            var user = await UserManager.GetUserAsync(User);
            try
            {
                var driver = DriverService.GetByUserId(user.Id);
                var routesHistoric = DriverService.GetRoutesHistory(driver.Id);
                var routesHistoricViewModel = new RoutesHistoryViewModel();
                routesHistoricViewModel.ConfigureRoutes(routesHistoric.Routes);
                return View(routesHistoricViewModel);
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve routes for current driver {@Exception}", e);
                Logger.LogError("Failed to retrieve routes for current driver {Exception}", e.Message);
                return BadRequest();
            }
        }
        public IActionResult Route(Guid id)
        {
            try
            {
                var route = DriverService.GetRouteById(id);

                return View(route);
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve route  {@Exception}", e);
                Logger.LogError("Failed to retrieve route  {Exception}", e.Message);
                return BadRequest();
            }
        }

        public IActionResult DriversTable()
        {
            //var x = DriverService.GetAllDrivers();
            try
            {
                var viewModel = new DriversViewModel
                {
                    Drivers = DriverService.GetAllDrivers()
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // public IActionResult GetDrivers()

        public IActionResult DetailsDriver(string id)
        {
            try
            {
                var driverId = Guid.Parse(id);

                var viewModel = new RoutesHistoryViewModel();
                viewModel.ConfigureRoutes(DriverService.GetRoutesHistory(driverId).Routes);

                return View("RoutesHistory", viewModel);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
        public async Task<IActionResult> Map()
        {
            var user = await UserManager.GetUserAsync(User);
            try
            {
                var driver = DriverService.GetByUserId(user.Id);
                var routeEntries = DriverService.GetRouteEntries(driver.Id);

                var currentRoute = new CurrentRouteViewModel();
                currentRoute.RouteEntries = routeEntries;
                currentRoute.DriverId = driver.Id;

                return View(currentRoute);
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve driver's route entries {@Exception}", e);
                Logger.LogError("Failed to retrieve driver's route entries{Exception}", e.Message);
                return BadRequest();
            }
        }
        public IActionResult RouteMap()
        {
            return View();

        }
        public IActionResult AvailableVehicles()
        {
            try
            {
                var vehicles = VehicleService.GetAvailableVehicles();
                return View(vehicles);
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to retrieve available vehicles {@Exception}", e);
                Logger.LogError("Failed to retrieve available vehicles {Exception}", e.Message);
                return BadRequest("Failed to retrieve available vehicles");
            }
        }
        public IActionResult GetPersonalInformations()
        {
            try
            {

                return PartialView("DriverInfo");
            }
            catch (Exception e)
            {
                Logger.LogDebug("Failed to get the current logged user {@Exception}", e);
                Logger.LogError("Failed to get the current logged user {Exception}", e.Message);
                return BadRequest("Failed to create a new vehicle change request");
            }
        }

    }
}

Licenta/Views/Drivers/AvailableVehicles.cshtml
@model IEnumerable<Licenta.Model.Vehicle>
@{
    ViewData["Title"] = "AvailableVehicles";
    Layout = null;
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<form asp-controller="Drivers" asp-action="VehicleChangeRequest">
    <label>Vehicle:</label>
    <input name="registrationNumber" type="text" list="vehicles" class="form-control" onchange="displayVehicleInfo()" id="vehicle" />
    <datalist id="vehicles">
        @if (Model != null && Model.Any())
            @foreach (var vehicle in Model)
            {
                <option>@vehicle.RegistrationNumber</option>
            }
    </datalist>
    <br />
    <b id="info"></b>
    <br />
    <br />
    <div class="d-flex justify-content-around">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        <button type="submit" id="confirm" class="btn bg-menu">Ok</button>

    </div>
</form>

<script>
    function displayVehicleInfo() {
        var registrationNumber = $('#vehicle').val();
        var model = @Html.Raw(Json.Serialize(Model));
        for (var i = 0; i < model.length; i++) {
            if (model[i].registrationNumber == registrationNumber) {
                $('#info').html('Name: ' + model[i].name + "<br/>VIN: " + model[i].vin);
            }
        }
    }

</script>

Licenta/Views/Drivers/DriverInfo.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model Licenta.ViewModels.Drivers.EditInfoViewModel


@{
    var user = UserManager.GetUserAsync(User).GetAwaiter().GetResult();

}
<form asp-controller="Drivers" asp-action="CreateEditInfoRequest" data-ajax="true">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input type="text" asp-for="Name" class="form-control" value="@user.UserName" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input type="text" asp-for="Email" class="form-control" value="@user.Email" />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber">PhoneNumber:</label>
        <input type="text" asp-for="PhoneNumber" class="form-control" value="@user.PhoneNumber" />
        <span asp-validation-for="PhoneNumber"></span>
    </div>
    <div class="d-flex justify-content-around">
        <input type="button" class="btn bg-danger" value="Cancel" data-dismiss="modal" />
        <input type="submit" class="btn bg-menu" value="Submit" onclick="closeModal('editPersonalInfo')"/>
    </div>
</form>

<script>
    function closeModal(id) {
        $('#' + id).modal('hide');
    }

</script>

Licenta/Views/Drivers/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@using Licenta.ViewModels.Drivers
@model CurrentRouteViewModel
<link rel="stylesheet" type="text/css" href="~/lib/datatables/datatables.min.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.bootstrap4.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.dataTables.min.css" />

@section Scripts {
    <script type="text/javascript" src="~/lib/datatables/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/datatables/Responsive-2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/jquery-cookie/jquery.cookie.js"></script>
}

<div class="row d-flex justify-content-between mt-3 mb-3 mr-auto">
    <h1 class="ml-3">Your orders</h1>
    <a id="mapButton" class="btn bg-menu" asp-action="RouteMap" asp-controller="Drivers" style="max-height:45px;text-align:center">Go to map</a>
</div>

<div id="OrdersTable">
    <partial name="_OrdersTablePartial.cshtml" model="@Model" />
</div>

<div>
    <div class="d-flex bd-highlight mb-3">
        <div class="p-2 flex-grow-1 bd-highlight">
            <button type="button" id="EndRoute" class="btn bg-menu btn-lg pull-right" data-toggle="modal" data-target="#RouteEnded">End Route</button>
            <h4 style="color:red" id="endRouteError"></h4>
        </div>
        <div class="p-2 bd-highlight">
            <button id="StartRoute" type="button" class="btn bg-menu btn-lg pull-right" data-toggle="modal" data-target="#RouteStarted">
                Start Route
            </button>
        </div>
    </div>
</div>

<div class="modal fade modal-delete" tabindex="-1" id="RouteEnded" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="max-width:60%">

            <div id="newPaymentBody" class="modal-body">
                <div class="text-center">
                    <p>Mark route as completed</p>
                </div>
                <div class="d-flex justify-content-around">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-success" onclick="EndRoute()">Ok</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade modal-delete" tabindex="-1" id="RouteStarted" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="max-width:60%">

            <div id="newPaymentBody" class="modal-body">
                <div class="text-center">
                    <p>Are you sure you want start the route?</p>
                </div>
                <div class="d-flex justify-content-around">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-success" onclick="StartRoute()">Yes</button>
                </div>
            </div>
        </div>
    </div>
</div>

<form method="post" asp-action="SetOrderStatus" asp-controller="Drivers" data-ajax="true" data-ajax-complete="realoadAfterCancelOrder()">
    <div class="modal fade modal-delete" tabindex="-1" id="CancelOrder" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="max-width:60%">

                <div id="newPaymentBody" class="modal-body">
                    <div class="text-center">
                        <p>This order will be cancelled</p>
                        <input type="hidden" name="status" id="statusCancel" />
                        <input type="hidden" name="orderId" id="orderCancel" />
                    </div>
                    <div class="d-flex justify-content-around">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-success">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<form method="post" asp-action="SetOrderStatus" asp-controller="Drivers" data-ajax="true" data-ajax-complete="tableReload()">
    <div class="modal fade modal-delete" tabindex="-1" id="OrderStatus" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="max-width:60%">

                <div id="newPaymentBody" class="modal-body">
                    <div class="text-center">
                        <p>Order status will be modified</p>
                        <input type="hidden" id="orderStatus" name="status" />
                        <input type="hidden" id="orderId" name="orderId" />
                        <input type="hidden" id="driverId" name="driverId" />
                        <input type="hidden" id="rowId" />
                    </div>
                    <div class="d-flex justify-content-around">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-success">Ok</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script>

    function clearDiv() {

        setTimeout( function () {
           $('#endRouteError').html("");
            } , 7000);
            }
    function EndRoute() {
        var ordersCounter = @Model.RouteEntries.Count;

        if (areOrdersCompleted() == false) {
            $('#endRouteError').html("Not all the orders are completed");
            $('#RouteEnded').modal('hide');
             clearDiv();
            return;
        }
        for (var i = 1; i <= ordersCounter; i++) {
            $.removeCookie('' + i);
        }
        $.removeCookie('StartRoute');
        window.location.href = '@Url.ActionLink("EndRoute", "Drivers")';

    }
    function StartRoute() {

        loadServerPartialView('#OrdersTable', "Drivers/StartRoute").done(function () {
             $('#Orders').DataTable({ responsive: true, lengthMenu: [5, 10, 15] });
             $('#RouteStarted').modal('hide');
            $('#StartRoute').prop('disabled', true);
             EnableButtons();
            $.cookie('StartRoute', true);
            $('#EndRoute').prop('disabled', false);
         })
    }
    $(document).ready(function () {
        $('#Orders').DataTable({ responsive: true, lengthMenu: [5, 10, 15] });
        setCookies();
        EnableButtons();
        var table = $('#Orders').DataTable();
 
        if ( !table.data().any() ) 
        {
            $('#StartRoute').prop('disabled', false);
            const mapButton = document.getElementById("mapButton");
            const classes = mapButton.classList;
            classes.add("disabled");
        }
        if ($('#StartRoute').is(":disabled") == false) {
            $('#EndRoute').prop('disabled', true);
        }
        else {
            $('$EndRoute').prop('disabled', false);
        }
    })
        function setCookies() {
        var ordersCounter = @Model.RouteEntries.Count;
        for (var i = 1; i <= ordersCounter; i++) {

            var buttonContent = $('#' + i).html();
            var cookieContent = $.cookie('' + i);
            if ($.cookie('' + i) != null) {

                if ($.cookie('' + i).search("Pick") > -1 && $('#' + i).html().search("Pick") > -1 ||
                   ($.cookie('' + i).search("Deliver") > -1 && $('#' + i).html().search("Deliver") > -1)) {

                    $('#' + i).html($.cookie('' + i));
                    if ($('#'+ i).html().indexOf('f') > -1)
                    {
                        $('#' + i).prop('disabled', true);
                        var cancelBtn = i + ordersCounter;
                        $('#' + cancelBtn).prop('disabled', true);
                    }

                }
            }
        }

            //$('#StartRoute').prop('disabled', $.cookie('StartRoute'));
    }

    function StatusUpdate(id) {
        var icon = "<em class='fas fa-check'></em>";
        var cancelBtn = @Model.RouteEntries.Count;
        cancelBtn = cancelBtn + parseInt(id);
        if ($('#' + id).html().search("Picked") > -1) {
            $('#' + id).html("PickedUp " + icon);
            $('#' + id).prop('disabled', true);
             $('#' + cancelBtn).prop('disabled', true);
            $.cookie(id, $('#' + id).html());
            }
        else if ($('#' + id).html().indexOf("Delivered") > -1) {

            $('#' + id).html("Delivered " + icon);
            $('#' + id).addClass('checked');
            $('#' + id).prop('disabled', true);
            $('#' + cancelBtn).prop('disabled', true);
             $.cookie(id, $('#' + id).html());
        }

    }
    function EnableButtons() {
        if ($('#StartRoute').is(':disabled'))
            {
            var ordersCounter = @Model.RouteEntries.Count;
            for (var i = 1; i <= ordersCounter; i++) {
                if($('#' + i).html().indexOf('f') == -1)
                    $("#" + i).prop('disabled', false);
                var cancelBtn = ordersCounter + i;
                if ($('#' + cancelBtn).html().indexOf('f') == -1 && $('#' + i).html().indexOf('f') == -1 ) {
                    $('#' + cancelBtn).prop('disabled', false);
                }
            }
        }
    }
    function tableReload() {
        loadServerPartialView('#OrdersTable', "Drivers/GetOrdersPartial").done(function () {
            $('#Orders').DataTable({ responsive: true, lengthMenu: [5, 10, 15] });
            $('#OrderStatus').modal('hide');
            setCookies();
            EnableButtons();
            StatusUpdate($('#rowId').val());
        })
    }
    function setOrderStatusModal(driverId,orderStatus,orderId,id) {
        $('#driverId').val(driverId);
        $('#orderStatus').val(orderStatus);
        $('#orderId').val(orderId);
        $('#rowId').val(id);
    }
    function areOrdersCompleted() {
         var ordersCounter = @Model.RouteEntries.Count;
        for (var i = 1; i <= ordersCounter; i++) {
            var cancelButtonId = i + ordersCounter;
            if ($('#' + i).html().indexOf('f') == -1 && $('#' +cancelButtonId).is(':disabled') == false) {
                return false;
            }
        }
        return true;
    }
    function setCancelOrderModal(OrderStatus , OrderId ) {
        $('#statusCancel').val(OrderStatus);
        $('#orderCancel').val(OrderId);

        }
        function realoadAfterCancelOrder() {

        loadServerPartialView('#OrdersTable', "Drivers/GetOrdersPartial").done(function () {
            $('#Orders').DataTable({ responsive: true, lengthMenu: [5, 10, 15] });
            $('#CancelOrder').modal('hide');
            EnableButtons();
            setCookies();

        })

    }
</script>

Licenta/Views/Drivers/Route.cshtml
@model Licenta.Model.Route
@{
    ViewData["Title"] = "Route";
}

<link rel="stylesheet" type="text/css" href="~/lib/datatables/datatables.min.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.bootstrap4.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.dataTables.min.css" />

@section Scripts {
    <script type="text/javascript" src="~/lib/datatables/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/datatables/Responsive-2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jquery-cookie/jquery.cookie.min.js"></script>

}

<h1 class="message-current-table mb-3">Route details</h1>

<table id="Orders" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th style="text-align:center"><b>PickUpAddress</b></th>
            <th style="text-align:center"><b>DeliveryAddress</b></th>
            <th style="text-align:center"><b>Payment</b></th>
            <th style="text-align:center"><b>PickUpTime</b></th>
            <th style="text-align:center"><b>DeliveryTime</b></th>


        </tr>
    </thead>
    <tbody>
        @foreach(var routeEntry in Model.RouteEntries)
        {
        <tr>
            <td style="text-align:center">
                <button class="btn btn-blue dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @routeEntry.Order.PickUpAddress.StreetNumber,@routeEntry.Order.PickUpAddress.Street
                </button>
                <div class="dropdown-menu" style="padding: 0.8rem">
                    <div>@routeEntry.Order.PickUpAddress.Country</div>
                    <div>@routeEntry.Order.PickUpAddress.City</div>
                </div>

            </td>
            <td style="text-align:center">
            <button class="btn btn-blue dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @routeEntry.Order.DeliveryAddress.StreetNumber,@routeEntry.Order.DeliveryAddress.Street
            </button>
            <div class="dropdown-menu" style="padding: 0.8rem">
                <div>@routeEntry.Order.DeliveryAddress.Country</div>
                <div>@routeEntry.Order.DeliveryAddress.City</div>
            </div>

            </td>
            <td style="text-align:center">@routeEntry.Order.Price</td>
            <td style="text-align:center"> @routeEntry.Order.PickUpTime.ToShortDateString() @routeEntry.Order.PickUpTime.ToString("HH:mm")</td>
            <td style="text-align:center" >@routeEntry.Order.DeliveryTime.ToShortDateString() @routeEntry.Order.DeliveryTime.ToString("HH:mm")</td>
        </tr>
        }
    </tbody>
</table>

<script>
    
    $(document).ready(function () {
        $('#Orders').DataTable({ responsive: true, lengthMenu: [5, 10, 15] });
    })

</script>

Licenta/Views/Drivers/RouteMap.cshtml
@{
    ViewData["Title"] = "RouteMap";
}

<h1>RouteMap</h1>

<iframe src="/Drivers/Map" style="margin-left:-200px;margin-top:-50px ;width:135%;height:570px"></iframe>