Licenta/ViewModels/Customers/AddressViewModel.cs
using Licenta.Model;
using System.Collections.Generic;

namespace Licenta.ViewModels.Customers
{
    public class AddressViewModel
    {
        public IEnumerable<LocationAddress> Addresses { get; set; }
    }
}

Licenta/ViewModels/Customers/CustomerListViewModel.cs
using Licenta.Model;
using System.Collections.Generic;

namespace Licenta.ViewModels.Customers
{
    public class CustomerListViewModel
    {
        public IEnumerable<Customer> CustomerViews { get; set; }
    }
}

Licenta/ViewModels/Customers/EditLocationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Customers
{
    public class EditLocationViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Country required")]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "City required")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Street required")]
        [Display(Name = "Street")]
        public string Street { get; set; }

        [Required]
        [Display(Name = "Street number")]
        public string StreetNumber { get; set; }

        [Required(ErrorMessage = "Postal Code required")]
        [Display(Name = "Postal Code")]
        public string PostalCode { get; set; }

        [Display(Name = "Tag")]
        public string Tag { get; set; }
    }
}

Licenta/ViewModels/Customers/NewCustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Customers
{
    public class NewCustomerViewModel
    {
        [Required(ErrorMessage = "Name required")]
        [Display(Name = "Full Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Phone number required")]
        [Display(Name = "Phone Number")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "Email required")]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

Licenta/ViewModels/Customers/NewLocationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Customers
{
    public class NewLocationViewModel
    {
        public string CustomerId { get; set; }

        [Required(ErrorMessage = "Country required")]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "City required")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Street required")]
        [Display(Name = "Street")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Street number required")]
        [Display(Name = "Street number")]
        public string StreetNumber { get; set; }

        [Required(ErrorMessage = "Postal Code required")]
        [Display(Name = "PostalCode")]
        public string PostalCode { get; set; }

        [Display(Name = "Tag")]
        public string Tag { get; set; }

    }
}

Licenta/ViewModels/Customers/OrderViewModel.cs
using System.Collections.Generic;
using Licenta.Model;

namespace Licenta.ViewModels.Customers
{
    public class OrderViewModel
    {
        public IEnumerable<Order> Orders { get; set; }
        public Customer Customer { get; set; }
        public int SelectedOrder { get; set; }
    }
}

Licenta/ViewModels/Customers/RemoveAddressViewModel.cs
namespace Licenta.ViewModels.Customers
{
    public class RemoveAddressViewModel
    {
        public string Id { get; set; }
    }
}

Licenta/ViewModels/Customers/RemoveCustomerViewModel.cs
namespace Licenta.ViewModels.Customers
{
    public class RemoveCustomerViewModel
    {
        public string Id { get; set; }
    }
}

Licenta/ViewModels/Customers/UpdateCustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Licenta.ViewModels.Customers
{
    public class UpdateCustomerViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Name missing!")]
        [Display(Name = "Full Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "PhoneNumber missing!")]
        [Display(Name = "Phone Number")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "Email missing!")]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

Licenta/Controllers/CustomersController.cs
using Licenta.Model;
using Licenta.ViewModels.Customers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;
using Licenta.AppLogic.Services;

namespace Licenta.Controllers
{
    public class CustomersController : Controller
    {
        private readonly CustomerService customerService;

        public CustomersController(CustomerService customerService)
        {
            this.customerService = customerService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CustomerTable()
        {
            CustomerListViewModel customerViewModel = null;
            try
            {
                customerViewModel = new CustomerListViewModel()
                {
                    CustomerViews = customerService.GetAllCustomers()
                };

            }
            catch (Exception)
            {
                //log
            }

            return PartialView("_CustomerTable", customerViewModel);
        }

        [HttpGet]
        public IActionResult UpdateCustomer([FromRoute] string id)
        {
            try
            {
                var customerToUpdate = customerService.GetCustomerById(id);

                var editCustomerViewModel = new UpdateCustomerViewModel()
                {
                    Id = id,
                    Name = customerToUpdate.Name,
                    PhoneNo = customerToUpdate.ContactDetails.PhoneNo,
                    Email = customerToUpdate.ContactDetails.Email
                };

                return PartialView("_UpdateCustomerPartial", editCustomerViewModel);

            }
            catch (Exception)
            {
                //log
                return BadRequest("Failed to edit customer entity");
            }
        }

        [HttpPost]
        public IActionResult UpdateCustomer([FromForm] UpdateCustomerViewModel updatedData, [FromRoute] string id)
        {
            if (updatedData.Name == null ||
                   updatedData.PhoneNo == null)
            {
                return PartialView("_UpdateCustomerPartial", new NewCustomerViewModel());
            }

            try
            {
                customerService.GetCustomerById(id);
                customerService.UpdateCustomer(Guid.Parse(id),
                                                updatedData.Name,
                                                updatedData.PhoneNo,
                                                updatedData.Email);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                //log
                return BadRequest("Failed to edit customer entity");
            }
        }
        [HttpGet]
        public IActionResult AddLocation()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var locationModel = new NewLocationViewModel()
            {

                CustomerId = userId
            };

            return PartialView("_AddLocationPartial", locationModel);
        }

        [HttpPost]
        public IActionResult AddLocation([FromForm] NewLocationViewModel locationData)
        {
            if (!ModelState.IsValid || locationData == null)
            {
                return PartialView("_AddLocationPartial", locationData);
            }

            try
            {
                var customer = customerService.GetCustomerById(locationData.CustomerId);

                var newLocation = LocationAddress.Create(
                            locationData.Country,
                            locationData.City,
                            locationData.Street,
                            locationData.StreetNumber,
                            locationData.PostalCode,
                            locationData.Tag);

                customerService.AddLocationToCustomer(customer.Id, newLocation);

                return RedirectToPage("/Account/Manage/PickupLocations", new { area = "Identity" });
            }
            catch (Exception) { return null; }

        }

        public IActionResult AddressTable()
        {
            var user = User.Identity.GetUserId();
            var addressView = new AddressViewModel()
            {
                Addresses = customerService.GetCustomerAddresses(user)
            };

            return PartialView("_AddressTablePartial", addressView);
        }


        [HttpGet]
        public IActionResult EditLocation([FromRoute] string id)
        {
            try
            {
                var locationToUpdate = customerService.GetLocationAddress(id);

                var editLocationViewModel = new EditLocationViewModel()
                {
                    Id = id,
                    Country = locationToUpdate.Country,
                    City = locationToUpdate.City,
                    Street = locationToUpdate.Street,
                    StreetNumber = locationToUpdate.StreetNumber,
                    PostalCode = locationToUpdate.PostalCode,
                    Tag = locationToUpdate.Tag
                };

                return PartialView("_EditLocationPartial", editLocationViewModel);

            }
            catch (Exception)
            {

                return BadRequest("Failed to update location entity");
            }
        }


        [HttpPost]
        public IActionResult EditLocation([FromForm] EditLocationViewModel updatedLocation)
        {
            if (!ModelState.IsValid || updatedLocation == null)
            {
                return PartialView("_EditLocationPartial", new EditLocationViewModel());
            }

            try
            {
                var locationToUpdate = customerService.GetLocationAddress(updatedLocation.Id);

                customerService.UpdateLocationAddress(locationToUpdate.Id,
                                updatedLocation.Country,
                                updatedLocation.City,
                                updatedLocation.Street,
                                updatedLocation.StreetNumber,
                                updatedLocation.PostalCode,
                                updatedLocation.Tag);

                return RedirectToPage("/Account/Manage/PickupLocations", new { area = "Identity" });
            }
            catch (Exception)
            {

                return BadRequest("Failed to edit location entity");
            }
        }


        [HttpGet]
        public IActionResult Remove([FromRoute] string id)
        {

            var removeViewModel = new RemoveCustomerViewModel()
            {
                Id = id
            };

            return PartialView("_RemoveCustomerPartial", removeViewModel);
        }

        [HttpPost]
        public IActionResult Remove(RemoveCustomerViewModel removeData)
        {
            try
            {
                customerService.RemoveCustomerById(removeData.Id);
            }
            catch (Exception)
            {
                //log
            }

            return PartialView("_RemoveCustomerPartial", removeData);
        }
    }

}

Licenta/Views/Customers/Index.cshtml
@using Licenta.ViewModels.Customers;

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" type="text/css" href="~/lib/datatables/datatables.min.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.bootstrap4.css" />
<link rel="stylesheet" type="text/css" href="~/lib/datatables/Responsive-2.2.3/css/responsive.dataTables.min.css" />

<div class="row d-flex justify-content-between mt-3 mb-3 mr-auto">
    <h1 class="ml-3">Customers</h1>
    <button class="btn-car" data-toggle="modal" data-target="#customerModal">New Customer <em class="fa fa-user"></em></button>
</div>

<div id="customerTableContainer"></div>

<form method="post" asp-controller="Customers" asp-action="UpdateCustomer"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="modalFormComplete('#updateCustomerModal')"
      data-ajax-mode="replace"
      data-ajax-update="#updateCustomerBody">

    <div class="modal fade" id="updateCustomerModal" tabindex="-1" role="dialog" aria-labelledby="UpdateCustomerTitle" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center">
            <div class="modal-content" style="max-width: 70%">
                <div class="modal-header">
                    <h5 class="modal-title" id="UpdateCustomerTitle">Update Information</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="updateCustomerBody">
                    <partial name="_UpdateCustomerPartial" model="new UpdateCustomerViewModel()" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Modify</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-controller="Customers" asp-action="CreateCustomer"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="modalFormComplete('#customerModal')"
      data-ajax-mode="replace"
      data-ajax-update="#customerBody">

    <div class="modal fade" id="customerModal" tabindex="-1" aria-labelledby="customerCreateTitle" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center">
            <div class="modal-content" style="max-width: 70%">
                <div class="modal-header">
                    <h5 class="modal-title" id="customerCreateTitle">Create a new entity</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="customerBody">
                    <partial name="_NewCustomerPartial" model="new NewCustomerViewModel()" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-controller="Customers" asp-action="AddLocation"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="modalFormComplete('#locationModal')"
      data-ajax-mode="replace"
      data-ajax-update="#locationBody">

    <div class="modal fade" id="locationModal" tabindex="-1" aria-labelledby="addLocationTitle" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center">
            <div class="modal-content" style="max-width: 70%">
                <div class="modal-header">
                    <h5 class="modal-title" id="addLocationTitle">Add a new location</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="locationBody">
                    <partial name="_AddLocationPartial" model="new NewLocationViewModel()" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Add Location</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-controller="Customers" asp-action="EditLocation"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="modalFormComplete('#editLocationModal')"
      data-ajax-mode="replace"
      data-ajax-update="#editLocationBody">

    <div class="modal fade" id="editLocationModal" tabindex="-1" aria-labelledby="editLocationTitle" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center">
            <div class="modal-content" style="max-width: 70%">
                <div class="modal-header">
                    <h5 class="modal-title" id="editLocationTitle">Edit location</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="editLocationBody">
                    <partial name="_EditLocationPartial" model="new EditLocationViewModel()" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-controller="Customers" asp-action="Remove"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-complete="modalFormComplete('#removeModal')"
      data-ajax-mode="replace"
      data-ajax-update="#removeBody">

    <div class="modal fade" style="margin-top:9rem;" id="removeModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog d-flex justify-content-center">
            <div class="modal-content" style="max-width: 60%">
                <div class="modal-body" id="removeBody">
                    <partial name="_RemoveCustomerPartial" model="new RemoveCustomerViewModel()" />
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script type="text/javascript" src="~/lib/datatables/datatables.min.js"></script>
    <script type="text/javascript" src="~/lib/datatables/Responsive-2.2.3/js/dataTables.responsive.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            loadTable();
        });

        function loadTable() {
            loadServerPartialView("#customerTableContainer", "/Customers/CustomerTable").done(function () {
                $('#customersTable').DataTable({ responsive: true, "lengthMenu": [5, 10, 25, 50] });
            });
        }

        function LoadRemoveCustomerView(Id) {
            loadServerPartialView("#removeBody", '@Url.Action("Remove", "Customers")' + "/" + Id);
        }

        function LoadAddLocationView(Id) {
            loadServerPartialView("#locationBody", '@Url.Action("AddLocation", "Customers")' + "/" + Id);
        }

        function LoadUpdateCustomerView(Id) {
            loadServerPartialView("#updateCustomerBody", '@Url.Action("UpdateCustomer", "Customers")' + "/" + Id);
        }

        function LoadEditLocationView(Id) {
            loadServerPartialView("#editLocationBody", '@Url.Action("EditLocation", "Customers")' + "/" + Id);
        }

        function modalFormComplete(modalName) {
            $(modalName).modal("hide");
            loadTable();
        }
    </script>
}

Licenta/Views/Customers/_AddLocationPartial.cshtml
@using Licenta.ViewModels.Customers;

@model NewLocationViewModel;

<input type="hidden" asp-for="CustomerId" />

<div class="form-group">
    <label asp-for="Country"></label>
    <input asp-for="Country" type="text" class="form-control" />
    <span asp-validation-for="Country" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="City"></label>
    <input asp-for="City" type="text" class="form-control" />
    <span asp-validation-for="City" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Street"></label>
    <input asp-for="Street" type="text" class="form-control" />
    <span asp-validation-for="Street" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="StreetNumber"></label>
    <input asp-for="StreetNumber" type="number" class="form-control" />
    <span asp-validation-for="StreetNumber" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PostalCode"></label>
    <input asp-for="PostalCode" type="text" class="form-control" />
    <span asp-validation-for="PostalCode" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Tag"></label>
    <input asp-for="Tag" type="text" class="form-control" />
    <span asp-validation-for="Tag" class="text-danger"></span>
</div>

Licenta/Views/Customers/_AddressTablePartial.cshtml
@using Licenta.ViewModels.Customers
@model AddressViewModel

<table id="addressTable" class="table table-borderless table-bordered" style="width:100%">
    <thead class="dropdown text-center">
        <tr>
            <th>Country</th>
            <th>City</th>
            <th>Street</th>
            <th>Street Number</th>
            <th>Postal Code</th>
            <th>Tag</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var address in Model.Addresses)
        {
            <tr>
                <td>@address.City</td>
                <td>@address.Country</td>
                <td>@address.Street</td>
                <td>@address.StreetNumber</td>
                <td>@address.PostalCode</td>
                @if(@address.Tag != null)
                {
                    <td>@address.Tag</td>
                }
                else
                {
                    <td>No tag created</td>
                }

                <td class="d-flex justify-content-around">

                    <button class="btn btn-outline-dark mr-1 ml-1"  title="Edit" data-toggle="modal"
                            data-target="#editLocationModal" onclick="LoadEditLocationView('@address.Id')">

                        <em class="material-icons fa fa-edit"></em>
                    </button>

                    <button class="btn btn-outline-danger mr-1 ml-1" title="Remove" data-toggle="modal"
                            onclick="LoadRemoveAddressView('@address.Id');" data-target="#removeModal">

                        <em class="material-icons fa fa-trash"></em>
                    </button>

                </td>
            </tr>
        }
    </tbody>
</table>

<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>

Licenta/Views/Customers/_CustomerTable.cshtml
@using Licenta.ViewModels.Customers;
@model CustomerListViewModel;

<table id="customersTable" class="table table-striped table-bordered" style="width:100%">
    <thead class="dropdown text-center">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Address</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var customer in Model.CustomerViews)
        {
            <tr>
                <td>@customer.Name</td>
                <td>@customer.ContactDetails.Email</td>
                <td>@customer.ContactDetails.PhoneNo</td>

                <td class="dropdown text-center">
                    <button class="btn btn-blue dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Address Locations (@customer.LocationAddresses.Count())
                    </button>
                    @if (customer.LocationAddresses.Count() > 0)
                    {
                    <div class="dropdown-menu dropdown-menu-right">
                        @foreach (var location in customer.LocationAddresses)
                        {
                        <button class="dropdown-item btn-blue edit-dropdown-item" data-toggle="modal"
                                onclick="LoadEditLocationView('@location.Id')" data-target="#editLocationModal">
                            <em class="fa fa-edit mr-2"></em>
                            @location.Country,
                            @location.City,
                            @location.Street,
                            @location.StreetNumber,
                            @location.PostalCode
                        </button>
                        }
                    </div>
                    }
                </td>

                <td style="max-width:20%">
                    <div class="d-flex justify-content-around">

                        <button class="btn btn-add-blue mr-1 ml-1" title="Add Location" data-toggle="modal"
                                onclick="LoadAddLocationView('@customer.Id')" data-target="#locationModal">
                            <em class="material-icons fa fa-plus"></em>
                        </button>

                        <button class="btn btn-outline-dark mr-1 ml-1" title="Edit" data-toggle="modal"
                                onclick="LoadUpdateCustomerView('@customer.Id');" data-target="#updateCustomerModal">
                            <em class="material-icons fa fa-edit"></em>
                        </button>
                        @if (User.IsInRole("Admin")) { 
                            <button class="btn btn-outline-danger mr-1 ml-1" title="Delete" data-toggle="modal"
                                    onclick="LoadRemoveCustomerView('@customer.Id');" data-target="#removeModal">
                                <em class="material-icons fa fa-trash"></em>
                            </button>
                        }
                        </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Licenta/Views/Customers/_EditLocationPartial.cshtml
@using Licenta.ViewModels.Customers;

@model EditLocationViewModel;

<input type="hidden" asp-for="Id" />

<div class="form-group">
    <label asp-for="Country"></label>
    <input asp-for="Country" type="text" class="form-control" />
    <span asp-validation-for="Country" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="City"></label>
    <input asp-for="City" type="text" class="form-control" />
    <span asp-validation-for="City" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Street"></label>
    <input asp-for="Street" type="text" class="form-control" />
    <span asp-validation-for="Street" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="StreetNumber"></label>
    <input asp-for="StreetNumber" type="number" class="form-control" />
    <span asp-validation-for="StreetNumber" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PostalCode"></label>
    <input asp-for="PostalCode" type="text" class="form-control" />
    <span asp-validation-for="PostalCode" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Tag"></label>
    <input asp-for="Tag" type="text" class="form-control" />
    <span asp-validation-for="Tag" class="text-danger"></span>
</div>

Licenta/Views/Customers/_NewCustomerPartial.cshtml
@using Licenta.ViewModels.Customers;
@model NewCustomerViewModel;

@{
    ViewData["Title"] = "Creating";
}

<div class="form-group">
    <label asp-for="Name"></label>
    <input asp-for="Name" type="text" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PhoneNo"></label>
    <input asp-for="PhoneNo" type="tel" class="form-control" />
    <span asp-validation-for="PhoneNo" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Email"></label>
    <input asp-for="Email" type="email" class="form-control" />
    <span asp-validation-for="Email" class="text-danger"></span>
</div>

Licenta/Views/Customers/_RemoveAddressPartial.cshtml
@using Licenta.ViewModels.Customers;

@model RemoveAddressViewModel;

<input type="hidden" asp-for="Id" />

<div class="text-center">
    <h2>Are you sure?</h2>
</div>

<div class="d-flex justify-content-around">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
    <button type="submit" class="btn btn-success">Yes</button>
</div>

Licenta/Views/Customers/_RemoveCustomerPartial.cshtml
@using Licenta.ViewModels.Customers;

@model RemoveCustomerViewModel;

<input type="hidden" asp-for="Id" />

<div class="text-center">
    <h2>Are you sure?</h2>
</div>

<div class="d-flex justify-content-around">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
    <button type="submit" class="btn btn-success">Yes</button>
</div>

Licenta/Views/Customers/_UpdateCustomerPartial.cshtml
@using Licenta.ViewModels.Customers;
@model UpdateCustomerViewModel;

@{
    ViewData["Title"] = "Creating";
}

<input type="hidden" asp-for="Id" />

<div class="form-group">
    <label asp-for="Name"></label>
    <input asp-for="Name" type="text" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="PhoneNo"></label>
    <input asp-for="PhoneNo" type="tel" class="form-control" />
    <span asp-validation-for="PhoneNo" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Email"></label>
    <input asp-for="Email" type="email" class="form-control" />
    <span asp-validation-for="Email" class="text-danger"></span>
</div>